### ISSUE TITLE
Probability calculator erroneous

### ISSUE THREAD

**Issue by ProbabilityCalculatorBug** [optc-db/optc-db.github.io#122]
The results of the propability calculator are always too low (mostly just a tiny bit).
This is especially apparent, when the calculator tells you that you have 0% success getting 1 skillup with 1 manual.

The reason for this is in file specialprobability.js, line 26:
`for (var i = skillups; i < copies; i++) {`

The loop terminates too early. Should be `i <= copies`.

**Comment by cgebe** [comment]
Reviewed and can confirm this. Bug initially committed by me.

**Comment by ProbabilityCalculatorBug** [comment]
Thanks
