### ISSUE TITLE
Treasure Turtle Evolutions

### ISSUE THREAD

**Issue by NeXoRaT** [optc-db/optc-db.github.io#30]
The evolutions for Treasure Turtles are slightly incorrect ;)

![turtle bug](https://cloud.githubusercontent.com/assets/18212785/14206531/f61983a6-f813-11e5-8c7e-349fde7d9396.png)

**Comment by optc-db** [comment]
The right Evolutions are saved in evolutions.js

So this must be a bug with CharUtils.searchEvolverEvolutions

Don't have time right now, but will hopefully get around to it eventually

It's also very low on priority since the right evolutions show up for both porc forms
