### ISSUE TITLE
"Farmable Sockets" Filter

### ISSUE THREAD

**Issue by Shotstic** [optc-db/optc-db.github.io#32]
I have mentioned this on the subreddit chat but I thought I'd make an official request. I think it'd be very useful to have a farmable socket filter. Example use: I want a 3+ socket STR slasher with farmable sockets to replace Arlong. ATM I either select farmable units and only look at those or include RR units and view each character's family one by one. If we could have a filter that includes both it'd be much appreciated. Thanks in advance and keep up the good work!

**Comment by optc-db** [comment]
I like the idea, should be up in a few
