### ISSUE TITLE
Borsalino CA and special

### ISSUE THREAD

**Issue by pesaher** [optc-db/optc-db.github.io#49]
When using two Borsalinos as captains, if you activate both specials and then deactivate one, his captain ability goes back to 2x even though there is still other special active. Also, if you export the link of the team after that situation, the error is kept when importing the team

**Comment by exoooM** [comment]
Error doesn't appear if you use ID1240 and ID1239 (6* and 5* Kizaru)

**Comment by pesaher** [comment]
Proof that it does happen: http://i.imgur.com/HwTOwkY.gifv

**Comment by JNathwani** [comment]
Fixed now with newest update
