### ISSUE TITLE
Damage Calculator issue with Legend Crocodie Special

### ISSUE THREAD

**Issue by offdev** [optc-db/optc-db.github.io#72]
Hi,

please check out following teams (the only change is the ship, which has the same damage multiplier, but gives more HP):
1) https://optc-db.github.io/damage/#/transfer/D720:99:100:100:0,720:99:100:100:0,1091:99:100:100:0,870:99:100:100:0,908:99:100:100:0,1322:99:100:100:0C16,10B0D0E1365Q0L0G0R37S0H
2) https://optc-db.github.io/damage/#/transfer/D720:99:100:100:0,720:99:100:100:0,1091:99:100:100:0,870:99:100:100:0,908:99:100:100:0,1322:99:100:100:0C13,10B0D0E1365Q0L0G0R37S0H

You can see the calculator indicates a different damage, while it should stay the same.

**Comment by Shotstic** [comment]
That's because 1HP means different percentages in those cases due to the difference in max HP, not sure how the game rounds numbers, though.

**Comment by JNathwani** [comment]
Seems to be fixed now, must have changed something that fixed it
