### ISSUE TITLE
Drag and Drop Error in Calc

### ISSUE THREAD

**Issue by optc-db** [optc-db/optc-db.github.io#73]
Droping the unit causes the Picker to open.

This is not a bug introduced by us but probably due to a Chrome Update.

The old calc has the same Problem in Chrome. Both work as intended in Firefox.

Same goes for the corresponding mobile browsers.

**Comment by Shotstic** [comment]
This doesn't happen when you drag and drop slowly, btw (just the drop part actually, you can drag as fast as you want). Only when you do it fast.
